# Generated by Django 3.0.2 on 2020-02-02 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='tags',
        ),
        migrations.AddField(
            model_name='tag',
            name='notes',
            field=models.ManyToManyField(to='restapi.Note'),
        ),
    ]
